name: Build and Deploy a Jekyll Site

on:
  push:
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2 # Not needed with a .ruby-version file
        bundler-cache: true
    - run: bundle exec jekyll build
    - name: Deploy site
      with:
        build-dir: _site
      uses:  NickSchimek/deploy_jamstack_action@main
